---
title: "close-elections-simsus"
author: "Vandrade"
date: "2024-09-29"
output: html_document
---

o foco da análise é o efeito de ter uma mulher como prefeita nos numeros de "deaths of despair" (Case & Deaton).

# Importando Bibliotecas
```{r}
library(tidyverse)
library(sf)
library(rdrobust) 
library(gt)
```


# Base TSE - Prefeitos

```{r}

prefeitos <- candidatos |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  arrange(desc(total_votos)) |> 
  slice_head(n = 2) |> 
  filter(any(is.na(genero)))
  

```


```{r}

candidatos <- readRDS("Dados/candidates.rds")

prefeitos <- candidatos |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  arrange(desc(total_votos)) |> 
  slice_head(n = 2) |> 
  filter(!is.na(genero)) |> 
  group_by(ano, estado, cd_municipio_tse) |> 
  filter(n_distinct(genero) == 2) |> 
  mutate(mg_fem = (total_votos[genero == 'FEMININO'] - total_votos[genero == 'MASCULINO'])/sum(total_votos),
         eleita = ifelse(mg_fem > 0, TRUE, FALSE),
         pop_total = pop_mas + pop_fem,
         educacao_agr = case_when(educacao %in% c('1º GRAU COMPLETO', '1º GRAU INCOMPLETO', 'ENSINO FUNDAMENTAL COMPLETO', 'ENSINO FUNDAMENTAL INCOMPLETO', 'FUNDAMENTAL COMPLETO', 'FUNDAMENTAL INCOMPLETO', 'ANALFABETO', 'LÊ E ESCREVE') ~ 'fundamental',
           educacao %in% c('2º GRAU COMPLETO', '2º GRAU INCOMPLETO', 'ENSINO MÉDIO COMPLETO', 'ENSINO MÉDIO INCOMPLETO', 'MÉDIO COMPLETO', 'MÉDIO INCOMPLETO') ~ 'medio',
           educacao %in% c('SUPERIOR COMPLETO', 'SUPERIOR INCOMPLETO') ~ 'superior',
           TRUE ~ NA_character_),
         codigo_ibge_sus = as.factor(codigo_ibge_sus)) |>
  filter(resultado == 'Eleito', pop_votante <= 200000) |> 
  ungroup()



```

```{r}

prefeitos %>% 
  ggplot(aes(x = mg_fem, fill = factor(eleita))) + 
  geom_histogram(boundary = 0, binwidth = 0.05, color = 'white') + 
  geom_vline(xintercept = 0) +
  scale_fill_manual(values = c("#e9d8a6", "#ae2012"),
                    labels = c("Homem Eleito", "Mulher Eleita")) +
  labs(title = "Distribuição de Margens de Vitória em Municípios Brasileiros",
       subtitle = "",
       x = "Margem de Vitória de Mulheres",
       y = NULL,
       fill = NULL) + 
  theme_minimal() + 
  theme(legend.position = "top",
        plot.caption = element_text(color = "#3494ba", size = 11),
        plot.title = element_text(size = 14),
        plot.subtitle = element_text(size = 11, color = 'black'),
        axis.title.y = element_text(margin = margin(r = 10, unit = "pt"), size = 11), 
        axis.title.x = element_text(margin = margin(t = 10, unit = "pt"), size = 11)) +
  scale_x_continuous(labels = scales::percent)

```



# Base DataSUS - SIM 

## Deaths of Despair
### Female
```{r}

simsus_mental_raw <- readRDS("Dados/simsus-mental.rds") 
  

simsus_mental_fem <- simsus_mental_raw |> 
  filter(idade_15_45 == TRUE, 
         sexo == 2) |> # 1- Masculino // 2 - Feminino
  mutate(cd_muni_ibge = as.numeric(cd_muni_ibge)) |> 
  group_by(mandato, cd_muni_ibge) |> 
  summarise(
    y_total_mental = sum(y_suicide == TRUE | y_alcoholic_disease == TRUE | y_overdose == TRUE),
    y_suicide = sum(y_suicide == TRUE),
    y_alcoholic_disease = sum(y_alcoholic_disease == TRUE),
    y_overdose = sum(y_overdose == TRUE)) 

```

```{r}

df_prefeitos_simsus <- prefeitos |> 
  left_join(simsus_mental_fem, by = c('ano' = 'mandato', 'codigo_ibge' = 'cd_muni_ibge')) |> 
  filter(ano >= 2004 & ano <= 2016) |> 
  mutate(codigo_ibge = as.factor(codigo_ibge),
         across(starts_with('y_'), ~ (./pop_total)*100000),
         across(starts_with('y_'), ~ replace_na(., 0)),
         ano = as.factor(ano),
         educacao_agr = as.factor(educacao_agr),
         partido = as.factor(partido)) 


```

```{r}
dependent <- c("y_total_mental",
               "y_suicide",
               "y_alcoholic_disease",
               "y_overdose")

results <- map_df(dependent, ~{rdrobust_result <- rdrobust(df_prefeitos_simsus[[.]], df_prefeitos_simsus$mg_fem,
                              # covs = controls,
                              c = 0,
                              kernel = 'uniform',
                              # h = 0.05, 
                              cluster = df_prefeitos_simsus$codigo_ibge)


  data.frame(
    'Variável_dependente' = .,
    Bandwidth = rdrobust_result$bws[1],
    Coeficiente = rdrobust_result$coef[3],
    'P_valor' = rdrobust_result$pv[3],
    'obs masculino' = rdrobust_result$N_h[1],
    'obs feminino' = rdrobust_result$N_h[2])})

  

results |>
  gt() |> 
  tab_header('rdd')
  # cols_label(y_total_mental = "Todos", y_suicide = 'Suicídio', y_alcoholic_disease = 'Doença alcoolica', y_overdose = 'Overdose')
```

```{r}
resultado <- rdrobust(y = df_prefeitos_simsus$y_suicide,
         x = df_prefeitos_simsus$mg_fem,
         kernel = 'triangular')

resultado |> summary()
```


```{r}

rdrobust(y = df_prefeitos_simsus$y_total_mental,
         x = df_prefeitos_simsus$mg_fem,
         cluster = df_prefeitos_simsus$codigo_ibge,
         kernel = 'triangular') |> summary()

 
lm(y_total_mental ~ eleita + ano * mg_fem  + prop_fem_pop, data = df_prefeitos_simsus |> filter(abs(mg_fem) <= .08)) |> summary()

lm(y_total_mental ~ eleita + ano, data = df_prefeitos_simsus) |> summary()


rdplot(y = df_prefeitos_simsus$y_overdose,
       x = df_prefeitos_simsus$mg_fem)

```

### Male
```{r}

simsus_mas <- simsus |> 
  filter(idade_15_45 == TRUE,
         sexo == 1) |> # 1- Masculino // 2 - Feminino
  group_by(mandato, cd_muni_ibge) |> 
  summarise(
    y_total_homicidio = n(),
    y_total_mental = sum(y_suicide == TRUE | y_alcoholic_disease == TRUE | y_overdose == TRUE),
    y_suicide = sum(y_suicide == TRUE),
    y_alcoholic_disease = sum(y_alcoholic_disease == TRUE),
    y_overdose = sum(y_overdose == TRUE)) 

```



## Homicidios

### Female - 15/49
```{r}

df_homicides <- readRDS("Dados/simsus-homicidio.rds") 

simsus_homicidio_fem <- df_homicides |> 
  filter(idade_15_49 == TRUE, 
         sexo == 2) |> # 1- Masculino // 2 - Feminino
  group_by(cd_muni_ibge, mandato) |> 
  summarise(y_homicide = sum(y_homicide == TRUE),
            y_domestic_homicide = sum(y_domestic_homicide == TRUE)) |> 
  ungroup() |> 
  mutate(cd_muni_ibge = as.factor(cd_muni_ibge))

```
## join
```{r}

df_homicidio_fem <- prefeitos |> 
  left_join(simsus_homicidio_fem, by = c('ano' = 'mandato', 'codigo_ibge_sus' = 'cd_muni_ibge')) |>
  filter(ano >= 2004 & ano <= 2012) |> 
  mutate(codigo_ibge = as.factor(codigo_ibge),
         across(starts_with('y_'), ~ (./pop_total)*100000),
         across(starts_with('y_'), ~ replace_na(., 0)),
         eleita = ifelse(genero == 'FEMININO', 1, 0),
         ano = as.factor(ano),
         educacao_agr = as.factor(educacao_agr),
         partido = as.factor(partido)) 


```


```{r}
rdplot(y = df_homicidio_fem$y_homicide, x = df_homicidio_fem$mg_fem,
       c = 0,
       nbins = c(50, 50),
       kernel = 'triangular',
       x.lim = c(-.20,.20))

```

```{r}
controls <- model.matrix(~ educacao_agr + pop_total + prop_fem_pop + ano + ano * mg_fem, data = df_homicidio_fem)


rdrobust(df_homicidio_fem$y_domestic_homicide, df_homicidio_fem$mg_fem,
         c = 0,
         kernel = 'triangular',
         cluster = df_homicidio_fem$codigo_ibge) |> summary()

```



```{r}
dependent <- c("y_homicide",
               "y_domestic_homicide")

results <- map_df(dependent, ~ {rdrobust_result <- rdrobust(y = df_homicidio_fem[[.]], x = df_homicidio_fem$mg_fem,
                              # covs = controls,
                              c = 0,
                              kernel = 'uniform',
                              # h = 0.05, 
                              cluster = df_homicidio_fem$codigo_ibge)


  data.frame(
    'Variável_dependente' = .,
    Bandwidth = rdrobust_result$bws[1],
    Coeficiente = rdrobust_result$coef[3],
    'P_valor' = rdrobust_result$pv[3],
    'obs masculino' = rdrobust_result$N_h[1],
    'obs feminino' = rdrobust_result$N_h[2])})

  

results |>
  gt() |> 
  tab_header('rdd')

```
























